# Spring properties
spring:
  application:
     name: musicianwealth-service  # Service registers under this name
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    cache: false             # Allow Thymeleaf templates to be reloaded at runtime

# Map the error path to error template (for Thymeleaf)
error:
  path: /error

# HTTP Server
server:
  port: 2228   # HTTP (Tomcat) port

# Discovery Server Access
#  1. DEV ONLY: Reduce the lease renewal interval to speed up registration
#  2. Define URL of registration server (defaultZone)
#  3. docker run -p 2228:2228 -h musicianwealthserver --net imarsnet --ip 172.18.0.11 -t imars/musicianwealth:latest
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.18.0.2:1111/eureka/ # config for dockerized deployment on the same host that docker daemon is running. (bridged network)
      #defaultZone: http://localhost:1111/eureka/ # config for development purposes on local computer  
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION

#  3. If using the Angel release-train ONLY, give the process a unique instance id 
#     so that multiple instances can register when running on SAME host.  This is
#     not needed since release-train Brixton.
#     NOTE-1: spring.application.instance_id is only set when run on Cloud Foundry,
#             so we fallback on the server-port when it is not defined
#     NOTE-2: Syntax ${x:${y}} = use $x if set, otherwise use $y
#   metadataMap:
#     instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
      


# application parameters
musicianwealth:
 validationMessage: Please validate your registration
