# Spring properties
spring:
  application:
     name: shopping-service  # Service registers under this name
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
  thymeleaf:
    cache: false             # Allow Thymeleaf templates to be reloaded at runtime

# Map the error path to error template (for Thymeleaf)
error:
  path: /error

# HTTP Server
server:
  port: 2232   # HTTP (Tomcat) port

# Discovery Server Access
#  1. DEV ONLY: Reduce the lease renewal interval to speed up registration
#  2. Define URL of registration server (defaultZone)
#  3. docker run -p 2232:2232 -h shoppingserver --net imarsnet --ip 172.18.0.13 -t imars/shopping:latest
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.18.0.2:1111/eureka/ # config for dockerized deployment on the same host that docker daemon is running. (bridged network)
      #defaultZone: http://localhost:1111/eureka/ # config for development purposes on local computer  
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION

#  3. If using the Angel release-train ONLY, give the process a unique instance id 
#     so that multiple instances can register when running on SAME host.  This is
#     not needed since release-train Brixton.
#     NOTE-1: spring.application.instance_id is only set when run on Cloud Foundry,
#             so we fallback on the server-port when it is not defined
#     NOTE-2: Syntax ${x:${y}} = use $x if set, otherwise use $y
#   metadataMap:
#     instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
      


# application parameters
asset:
 wealthServiceUrl : http://localhost:2228/musicianwealth
 instruments: 
    - lespaul-guitar.5000
    - yamaha-bass.5000
    - yamaha-stage-custom.5000
 estates:
    - apartment.100000
    - house.150000
 cars:
    - sports.75000
    - racing.100000
    - standard.20000   